name: Green Code Conversion

on:
  push:
    branches:
      - main
      
permissions:
  contents: write 
  
jobs:
  convert-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: pip install requests

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Create new branch 
        run: git checkout -b "greencode-${{ github.sha }}"

      - name: Run green code optimizer
        env:
          GREEN_API_URL: ${{ secrets.GREEN_API_URL }}
        run: python3 optimize_code.py

      - name: Check for changes
        run: |
          git status
          git diff

      - name: Commit and push 
        run: |
          git add .
          git commit -m "Converted code to green code" || echo "No changes to commit"
          git push origin "greencode-${{ github.sha }}"
